USE banco_bd;

CREATE TABLE IF NOT EXISTS cliente (
  id_cliente BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tipo_cliente_id BIGINT UNSIGNED NOT NULL,
  estado_cliente_id BIGINT UNSIGNED NOT NULL,
  id_identificacion VARCHAR(50) NOT NULL,
  nombre_completo VARCHAR(200) NOT NULL,
  correo_electronico VARCHAR(255) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  direccion VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_cliente),
  UNIQUE KEY uk_cliente_id_identificacion (id_identificacion),
  KEY idx_cliente_estado_cliente (estado_cliente_id),
  KEY idx_cliente_tipo_cliente (tipo_cliente_id),
  CONSTRAINT fk_cliente_tipo_cliente FOREIGN KEY (tipo_cliente_id) REFERENCES cat_tipo_cliente (id_catalogo),
  CONSTRAINT fk_cliente_estado_cliente FOREIGN KEY (estado_cliente_id) REFERENCES cat_estado_cliente (id_catalogo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS cliente_persona (
  id_cliente BIGINT UNSIGNED NOT NULL,
  nombres VARCHAR(120) NOT NULL,
  apellidos VARCHAR(120) NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_cliente),
  CONSTRAINT fk_cliente_persona_cliente FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS cliente_empresa (
  id_cliente BIGINT UNSIGNED NOT NULL,
  razon_social VARCHAR(200) NOT NULL,
  nit VARCHAR(30) NOT NULL,
  id_representante_legal BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_cliente),
  UNIQUE KEY uk_cliente_empresa_nit (nit),
  KEY idx_cliente_empresa_representante_legal (id_representante_legal),
  CONSTRAINT fk_cliente_empresa_cliente FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
  CONSTRAINT fk_cliente_empresa_representante FOREIGN KEY (id_representante_legal) REFERENCES cliente_persona (id_cliente)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS empleado (
  id_empleado BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tipo_empleado_id BIGINT UNSIGNED NOT NULL,
  estado_empleado_id BIGINT UNSIGNED NOT NULL,
  id_identificacion VARCHAR(50) NOT NULL,
  nombres VARCHAR(120) NOT NULL,
  apellidos VARCHAR(120) NOT NULL,
  cargo VARCHAR(120) NOT NULL,
  area VARCHAR(120) NOT NULL,
  correo_interno VARCHAR(255) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_empleado),
  UNIQUE KEY uk_empleado_id_identificacion (id_identificacion),
  KEY idx_empleado_tipo_empleado (tipo_empleado_id),
  KEY idx_empleado_estado_empleado (estado_empleado_id),
  CONSTRAINT fk_empleado_tipo_empleado FOREIGN KEY (tipo_empleado_id) REFERENCES cat_tipo_empleado (id_catalogo),
  CONSTRAINT fk_empleado_estado_empleado FOREIGN KEY (estado_empleado_id) REFERENCES cat_estado_empleado (id_catalogo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS usuario_sistema (
  id_usuario BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_cliente BIGINT UNSIGNED NULL,
  id_empleado BIGINT UNSIGNED NULL,
  rol_sistema_id BIGINT UNSIGNED NOT NULL,
  estado_usuario_id BIGINT UNSIGNED NOT NULL,
  nombre_completo VARCHAR(200) NOT NULL,
  id_identificacion VARCHAR(50) NOT NULL,
  contrasena_hash VARCHAR(255) NOT NULL,
  correo_electronico VARCHAR(255) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  fecha_nacimiento DATE NULL,
  direccion VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_usuario),
  UNIQUE KEY uk_usuario_id_identificacion (id_identificacion),
  KEY idx_usuario_rol_sistema (rol_sistema_id),
  KEY idx_usuario_estado_usuario (estado_usuario_id),
  KEY idx_usuario_cliente (id_cliente),
  KEY idx_usuario_empleado (id_empleado),
  CONSTRAINT fk_usuario_cliente FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
  CONSTRAINT fk_usuario_empleado FOREIGN KEY (id_empleado) REFERENCES empleado (id_empleado),
  CONSTRAINT fk_usuario_rol_sistema FOREIGN KEY (rol_sistema_id) REFERENCES cat_rol_sistema (id_catalogo),
  CONSTRAINT fk_usuario_estado_usuario FOREIGN KEY (estado_usuario_id) REFERENCES cat_estado_usuario (id_catalogo),
  CONSTRAINT ck_usuario_unico_vinculo CHECK ((id_cliente IS NULL) <> (id_empleado IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS producto_bancario (
  id_producto BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  codigo_producto VARCHAR(40) NOT NULL,
  nombre_producto VARCHAR(150) NOT NULL,
  categoria_producto_id BIGINT UNSIGNED NOT NULL,
  estado_producto_id BIGINT UNSIGNED NOT NULL,
  requiere_aprobacion TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_producto),
  UNIQUE KEY uk_producto_codigo (codigo_producto),
  KEY idx_producto_categoria (categoria_producto_id),
  KEY idx_producto_estado (estado_producto_id),
  CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_producto_id) REFERENCES cat_categoria_producto (id_catalogo),
  CONSTRAINT fk_producto_estado FOREIGN KEY (estado_producto_id) REFERENCES cat_estado_producto (id_catalogo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS cliente_asignacion_comercial (
  id_asignacion BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_cliente BIGINT UNSIGNED NOT NULL,
  id_empleado_comercial BIGINT UNSIGNED NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NULL,
  observacion VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_asignacion),
  KEY idx_asignacion_cliente (id_cliente),
  KEY idx_asignacion_empleado (id_empleado_comercial),
  CONSTRAINT fk_asignacion_cliente FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
  CONSTRAINT fk_asignacion_empleado FOREIGN KEY (id_empleado_comercial) REFERENCES empleado (id_empleado),
  CONSTRAINT ck_asignacion_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS cuenta (
  id_cuenta BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  numero_cuenta VARCHAR(30) NOT NULL,
  id_titular_cliente BIGINT UNSIGNED NOT NULL,
  tipo_cuenta_id BIGINT UNSIGNED NOT NULL,
  moneda_id BIGINT UNSIGNED NOT NULL,
  estado_cuenta_id BIGINT UNSIGNED NOT NULL,
  saldo_actual DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  fecha_apertura DATE NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_cuenta),
  UNIQUE KEY uk_cuenta_numero_cuenta (numero_cuenta),
  KEY idx_cuenta_titular (id_titular_cliente),
  KEY idx_cuenta_estado (estado_cuenta_id),
  KEY idx_cuenta_titular_estado (id_titular_cliente, estado_cuenta_id),
  CONSTRAINT fk_cuenta_titular FOREIGN KEY (id_titular_cliente) REFERENCES cliente (id_cliente),
  CONSTRAINT fk_cuenta_tipo FOREIGN KEY (tipo_cuenta_id) REFERENCES cat_tipo_cuenta (id_catalogo),
  CONSTRAINT fk_cuenta_moneda FOREIGN KEY (moneda_id) REFERENCES cat_moneda (id_catalogo),
  CONSTRAINT fk_cuenta_estado FOREIGN KEY (estado_cuenta_id) REFERENCES cat_estado_cuenta (id_catalogo),
  CONSTRAINT ck_cuenta_saldo_no_negativo CHECK (saldo_actual >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS cuenta_movimiento (
  id_movimiento BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_cuenta BIGINT UNSIGNED NOT NULL,
  tipo_movimiento_id BIGINT UNSIGNED NOT NULL,
  monto DECIMAL(18,2) NOT NULL,
  saldo_anterior DECIMAL(18,2) NOT NULL,
  saldo_posterior DECIMAL(18,2) NOT NULL,
  referencia_tipo VARCHAR(60) NOT NULL,
  referencia_id VARCHAR(64) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_movimiento),
  KEY idx_movimiento_cuenta_fecha (id_cuenta, created_at),
  KEY idx_movimiento_referencia (referencia_tipo, referencia_id),
  CONSTRAINT fk_movimiento_cuenta FOREIGN KEY (id_cuenta) REFERENCES cuenta (id_cuenta),
  CONSTRAINT fk_movimiento_tipo FOREIGN KEY (tipo_movimiento_id) REFERENCES cat_tipo_movimiento_cuenta (id_catalogo),
  CONSTRAINT ck_movimiento_importes CHECK (monto > 0 AND saldo_anterior >= 0 AND saldo_posterior >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS prestamo (
  id_prestamo BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tipo_prestamo_id BIGINT UNSIGNED NOT NULL,
  id_cliente_solicitante BIGINT UNSIGNED NOT NULL,
  monto_solicitado DECIMAL(18,2) NOT NULL,
  monto_aprobado DECIMAL(18,2) NULL,
  tasa_interes DECIMAL(9,4) NOT NULL,
  plazo_meses INT NOT NULL,
  estado_prestamo_id BIGINT UNSIGNED NOT NULL,
  fecha_solicitud DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_aprobacion DATETIME NULL,
  fecha_desembolso DATETIME NULL,
  id_cuenta_destino_desembolso BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_prestamo),
  KEY idx_prestamo_cliente (id_cliente_solicitante),
  KEY idx_prestamo_estado (estado_prestamo_id),
  KEY idx_prestamo_fecha_solicitud (fecha_solicitud),
  KEY idx_prestamo_cuenta_desembolso (id_cuenta_destino_desembolso),
  CONSTRAINT fk_prestamo_tipo FOREIGN KEY (tipo_prestamo_id) REFERENCES cat_tipo_prestamo (id_catalogo),
  CONSTRAINT fk_prestamo_cliente FOREIGN KEY (id_cliente_solicitante) REFERENCES cliente (id_cliente),
  CONSTRAINT fk_prestamo_estado FOREIGN KEY (estado_prestamo_id) REFERENCES cat_estado_prestamo (id_catalogo),
  CONSTRAINT fk_prestamo_cuenta_desembolso FOREIGN KEY (id_cuenta_destino_desembolso) REFERENCES cuenta (id_cuenta),
  CONSTRAINT ck_prestamo_importes CHECK (monto_solicitado > 0 AND tasa_interes > 0 AND plazo_meses > 0 AND (monto_aprobado IS NULL OR monto_aprobado <= monto_solicitado))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS prestamo_aprobacion (
  id_prestamo_aprobacion BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_prestamo BIGINT UNSIGNED NOT NULL,
  id_usuario_aprobador BIGINT UNSIGNED NOT NULL,
  decision_id BIGINT UNSIGNED NOT NULL,
  observacion VARCHAR(255) NULL,
  fecha_decision DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_prestamo_aprobacion),
  KEY idx_prestamo_aprobacion_prestamo (id_prestamo),
  KEY idx_prestamo_aprobacion_usuario (id_usuario_aprobador),
  CONSTRAINT fk_prestamo_aprobacion_prestamo FOREIGN KEY (id_prestamo) REFERENCES prestamo (id_prestamo),
  CONSTRAINT fk_prestamo_aprobacion_usuario FOREIGN KEY (id_usuario_aprobador) REFERENCES usuario_sistema (id_usuario),
  CONSTRAINT fk_prestamo_aprobacion_decision FOREIGN KEY (decision_id) REFERENCES cat_decision_aprobacion (id_catalogo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS prestamo_desembolso (
  id_prestamo_desembolso BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_prestamo BIGINT UNSIGNED NOT NULL,
  id_cuenta_destino BIGINT UNSIGNED NOT NULL,
  monto_desembolsado DECIMAL(18,2) NOT NULL,
  fecha_desembolso DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_usuario_ejecutor BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_prestamo_desembolso),
  KEY idx_prestamo_desembolso_prestamo (id_prestamo),
  KEY idx_prestamo_desembolso_cuenta (id_cuenta_destino),
  CONSTRAINT fk_prestamo_desembolso_prestamo FOREIGN KEY (id_prestamo) REFERENCES prestamo (id_prestamo),
  CONSTRAINT fk_prestamo_desembolso_cuenta FOREIGN KEY (id_cuenta_destino) REFERENCES cuenta (id_cuenta),
  CONSTRAINT fk_prestamo_desembolso_usuario FOREIGN KEY (id_usuario_ejecutor) REFERENCES usuario_sistema (id_usuario),
  CONSTRAINT ck_prestamo_desembolso_monto CHECK (monto_desembolsado > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS transferencia (
  id_transferencia BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cuenta_origen_id BIGINT UNSIGNED NOT NULL,
  cuenta_destino_id BIGINT UNSIGNED NOT NULL,
  monto DECIMAL(18,2) NOT NULL,
  estado_transferencia_id BIGINT UNSIGNED NOT NULL,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_aprobacion DATETIME NULL,
  fecha_ejecucion DATETIME NULL,
  fecha_vencimiento DATETIME NULL,
  id_usuario_creador BIGINT UNSIGNED NOT NULL,
  id_usuario_aprobador BIGINT UNSIGNED NULL,
  observacion VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_transferencia),
  KEY idx_transferencia_origen (cuenta_origen_id),
  KEY idx_transferencia_destino (cuenta_destino_id),
  KEY idx_transferencia_estado (estado_transferencia_id),
  KEY idx_transferencia_fecha_creacion (fecha_creacion),
  KEY idx_transferencia_fecha_vencimiento (fecha_vencimiento),
  KEY idx_transferencia_usuario_creador (id_usuario_creador),
  KEY idx_transferencia_usuario_aprobador (id_usuario_aprobador),
  CONSTRAINT fk_transferencia_origen FOREIGN KEY (cuenta_origen_id) REFERENCES cuenta (id_cuenta),
  CONSTRAINT fk_transferencia_destino FOREIGN KEY (cuenta_destino_id) REFERENCES cuenta (id_cuenta),
  CONSTRAINT fk_transferencia_estado FOREIGN KEY (estado_transferencia_id) REFERENCES cat_estado_transferencia (id_catalogo),
  CONSTRAINT fk_transferencia_creador FOREIGN KEY (id_usuario_creador) REFERENCES usuario_sistema (id_usuario),
  CONSTRAINT fk_transferencia_aprobador FOREIGN KEY (id_usuario_aprobador) REFERENCES usuario_sistema (id_usuario),
  CONSTRAINT ck_transferencia_monto CHECK (monto > 0),
  CONSTRAINT ck_transferencia_cuentas CHECK (cuenta_origen_id <> cuenta_destino_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS transferencia_aprobacion (
  id_transferencia_aprobacion BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_transferencia BIGINT UNSIGNED NOT NULL,
  id_usuario_aprobador BIGINT UNSIGNED NOT NULL,
  decision_id BIGINT UNSIGNED NOT NULL,
  observacion VARCHAR(255) NULL,
  fecha_decision DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_transferencia_aprobacion),
  KEY idx_transferencia_aprobacion_transferencia (id_transferencia),
  KEY idx_transferencia_aprobacion_usuario (id_usuario_aprobador),
  CONSTRAINT fk_transferencia_aprobacion_transferencia FOREIGN KEY (id_transferencia) REFERENCES transferencia (id_transferencia),
  CONSTRAINT fk_transferencia_aprobacion_usuario FOREIGN KEY (id_usuario_aprobador) REFERENCES usuario_sistema (id_usuario),
  CONSTRAINT fk_transferencia_aprobacion_decision FOREIGN KEY (decision_id) REFERENCES cat_decision_aprobacion (id_catalogo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS solicitud_producto (
  id_solicitud_producto BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_cliente_solicitante BIGINT UNSIGNED NOT NULL,
  id_producto BIGINT UNSIGNED NOT NULL,
  estado_solicitud_id BIGINT UNSIGNED NOT NULL,
  id_usuario_gestor BIGINT UNSIGNED NULL,
  fecha_solicitud DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  observacion TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_solicitud_producto),
  KEY idx_solicitud_producto_cliente (id_cliente_solicitante),
  KEY idx_solicitud_producto_estado (estado_solicitud_id),
  KEY idx_solicitud_producto_fecha (fecha_solicitud),
  CONSTRAINT fk_solicitud_producto_cliente FOREIGN KEY (id_cliente_solicitante) REFERENCES cliente (id_cliente),
  CONSTRAINT fk_solicitud_producto_producto FOREIGN KEY (id_producto) REFERENCES producto_bancario (id_producto),
  CONSTRAINT fk_solicitud_producto_estado FOREIGN KEY (estado_solicitud_id) REFERENCES cat_estado_solicitud_producto (id_catalogo),
  CONSTRAINT fk_solicitud_producto_gestor FOREIGN KEY (id_usuario_gestor) REFERENCES usuario_sistema (id_usuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS pago_masivo (
  id_pago_masivo BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_cliente_empresa BIGINT UNSIGNED NOT NULL,
  id_cuenta_origen BIGINT UNSIGNED NOT NULL,
  id_usuario_creador BIGINT UNSIGNED NOT NULL,
  estado_pago_masivo_id BIGINT UNSIGNED NOT NULL,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_aprobacion DATETIME NULL,
  fecha_ejecucion DATETIME NULL,
  observacion VARCHAR(255) NULL,
  total_monto DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  cantidad_detalles INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_pago_masivo),
  KEY idx_pago_masivo_empresa (id_cliente_empresa),
  KEY idx_pago_masivo_cuenta (id_cuenta_origen),
  KEY idx_pago_masivo_estado (estado_pago_masivo_id),
  CONSTRAINT fk_pago_masivo_empresa FOREIGN KEY (id_cliente_empresa) REFERENCES cliente_empresa (id_cliente),
  CONSTRAINT fk_pago_masivo_cuenta FOREIGN KEY (id_cuenta_origen) REFERENCES cuenta (id_cuenta),
  CONSTRAINT fk_pago_masivo_usuario FOREIGN KEY (id_usuario_creador) REFERENCES usuario_sistema (id_usuario),
  CONSTRAINT fk_pago_masivo_estado FOREIGN KEY (estado_pago_masivo_id) REFERENCES cat_estado_pago_masivo (id_catalogo),
  CONSTRAINT ck_pago_masivo_importes CHECK (total_monto >= 0 AND cantidad_detalles >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS pago_masivo_detalle (
  id_pago_masivo_detalle BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_pago_masivo BIGINT UNSIGNED NOT NULL,
  id_cuenta_destino BIGINT UNSIGNED NOT NULL,
  monto DECIMAL(18,2) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_pago_masivo_detalle),
  KEY idx_pago_masivo_detalle_pago (id_pago_masivo),
  KEY idx_pago_masivo_detalle_cuenta (id_cuenta_destino),
  CONSTRAINT fk_pago_masivo_detalle_pago FOREIGN KEY (id_pago_masivo) REFERENCES pago_masivo (id_pago_masivo),
  CONSTRAINT fk_pago_masivo_detalle_cuenta FOREIGN KEY (id_cuenta_destino) REFERENCES cuenta (id_cuenta),
  CONSTRAINT ck_pago_masivo_detalle_monto CHECK (monto > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS delegacion_permiso (
  id_delegacion_permiso BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_cliente_empresa BIGINT UNSIGNED NOT NULL,
  id_usuario_delegado BIGINT UNSIGNED NOT NULL,
  tipo_permiso_id BIGINT UNSIGNED NOT NULL,
  estado_delegacion_id BIGINT UNSIGNED NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NULL,
  observacion VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id_delegacion_permiso),
  KEY idx_delegacion_empresa (id_cliente_empresa),
  KEY idx_delegacion_usuario (id_usuario_delegado),
  KEY idx_delegacion_estado (estado_delegacion_id),
  CONSTRAINT fk_delegacion_empresa FOREIGN KEY (id_cliente_empresa) REFERENCES cliente_empresa (id_cliente),
  CONSTRAINT fk_delegacion_usuario FOREIGN KEY (id_usuario_delegado) REFERENCES usuario_sistema (id_usuario),
  CONSTRAINT fk_delegacion_tipo_permiso FOREIGN KEY (tipo_permiso_id) REFERENCES cat_tipo_permiso (id_catalogo),
  CONSTRAINT fk_delegacion_estado FOREIGN KEY (estado_delegacion_id) REFERENCES cat_estado_delegacion (id_catalogo),
  CONSTRAINT ck_delegacion_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bitacora_operacion (
  id_bitacora BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tipo_operacion_id BIGINT UNSIGNED NOT NULL,
  fecha_hora_operacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_usuario BIGINT UNSIGNED NOT NULL,
  rol_usuario VARCHAR(80) NOT NULL,
  id_producto_afectado VARCHAR(64) NULL,
  datos_detalle JSON NOT NULL,
  trace_id VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_bitacora),
  KEY idx_bitacora_fecha (fecha_hora_operacion),
  KEY idx_bitacora_usuario (id_usuario),
  KEY idx_bitacora_tipo_operacion (tipo_operacion_id),
  CONSTRAINT fk_bitacora_tipo_operacion FOREIGN KEY (tipo_operacion_id) REFERENCES cat_tipo_operacion_bitacora (id_catalogo),
  CONSTRAINT fk_bitacora_usuario FOREIGN KEY (id_usuario) REFERENCES usuario_sistema (id_usuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;